version: "3.3"

services:
  #db:
   # image: postgres
    #restart: always
    #environment:
     # POSTGRES_PASSWORD: pahzzwor7676
    #ports:
     # - "5432:5432"
  app:
    build: .
    ports:
      - 8081:81
    #depends_on:
     # - db
    environment:
    - POSTGRES_PASSWORD:pahzzwor7676
  webserver:
    image: nginx
    ports:
      - "8081:81"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=81
