version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD:pahzzwor7676
    - POSTGRES_DB:MyAnimalDb
    - POSTGRES_USER:mattUser
  app:
    build: .
    ports:
      - 8000:80
    depends_on:
      - db
