version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
     POSTGRES_PASSWORD: pahzzwor7676
  app:
    build: .
    ports:
      - 5000:80
    depends_on:
     - db
    environment:
    - POSTGRES_PASSWORD:pahzzwor7676